CSRCS += $(wildcard $(LVGL_DIR)/src/*.c)
CSRCS += $(wildcard $(LVGL_DIR)/src/generated/*.c)

CSRCS += $(wildcard $(LVGL_DIR)/src/generated/aircon_cool/*.c)
CSRCS += $(wildcard $(LVGL_DIR)/src/generated/aircon_fan/*.c)
CSRCS += $(wildcard $(LVGL_DIR)/src/generated/aircon_menu_cool/*.c)
CSRCS += $(wildcard $(LVGL_DIR)/src/generated/aircon_menu_fan/*.c)
CSRCS += $(wildcard $(LVGL_DIR)/src/generated/aircon_menu_swing/*.c)
CSRCS += $(wildcard $(LVGL_DIR)/src/generated/aircon_screen/*.c)
CSRCS += $(wildcard $(LVGL_DIR)/src/generated/aircon_swing/*.c)
CSRCS += $(wildcard $(LVGL_DIR)/src/generated/hood_screen/*.c)
CSRCS += $(wildcard $(LVGL_DIR)/src/generated/oven_door/*.c)
CSRCS += $(wildcard $(LVGL_DIR)/src/generated/oven_fan/*.c)
CSRCS += $(wildcard $(LVGL_DIR)/src/generated/oven_menu_door/*.c)
CSRCS += $(wildcard $(LVGL_DIR)/src/generated/oven_menu_fan/*.c)
CSRCS += $(wildcard $(LVGL_DIR)/src/generated/oven_screen/*.c)
