#!/usr/bin/env python3
# -*- coding: utf-8 -*-

# Copyright 2023 NXP
# SPDX-License-Identifier: BSD-3-Clause

import json
import posix_ipc
import time
import sys

if __name__ == "__main__":
    mq = posix_ipc.MessageQueue("/wakeword_queue")
    #Enqueue with send, str,Send unicode
    params = sys.argv[1]
    mq.send(params)

    print("running " + sys.argv[0])
    print("wakeword id: " + sys.argv[1])
    print("ended")
